# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-18 02:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aristotle_mdr_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aristotletoken',
            name='name',
            field=models.CharField(default='Token', max_length=100),
        ),
    ]
