# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-18 02:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aristotle_mdr_api', '0002_aristotletoken_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aristotletoken',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auth_token', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
