# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-18 03:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aristotle_mdr_api', '0003_auto_20180518_0243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aristotletoken',
            name='key',
            field=models.CharField(max_length=40, verbose_name='Key'),
        ),
        migrations.AddField(
            model_name='aristotletoken',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        )
    ]
