# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-04 04:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid

from aristotle_mdr.utils.migrations import create_uuid_objects

class Migration(migrations.Migration):

    dependencies = [
        ('aristotle_mdr', '0022_switch_to_concept_relations'),
    ]

    operations = [
        migrations.CreateModel(
            name='UUID',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid1, editable=False, help_text='Universally-unique Identifier. Uses UUID1 as this improves uniqueness and tracking between registries', primary_key=True, serialize=False, unique=True)),
                ('app_label', models.CharField(editable=False, max_length=256)),
                ('model_name', models.CharField(editable=False, max_length=256)),
            ],
        ),
    ]
