# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-04 04:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid

from aristotle_mdr.utils.migrations import create_uuid_objects, classproperty, DBOnlySQL

class Migration(migrations.Migration):

    @classproperty
    def dependencies(cls):
        deps = [
            ('aristotle_mdr', '0023_uuid_model'),
            ('aristotle_mdr_links', '0005_switch_to_concept_relations'),
            ('aristotle_mdr_slots', '0004_switch_to_concept_relations'),
        ]
        from django.conf import settings

        if "aristotle_multisite" in settings.INSTALLED_APPS:
            deps.append(
                ('aristotle_multisite', '0001_initial'),
            )

        return deps

    operations = [
        # This is needed as we modify ForeignKeys before they are made during the migration
        migrations.RunSQL(
            'SET CONSTRAINTS ALL IMMEDIATE;',
            reverse_sql=migrations.RunSQL.noop
        ),

        migrations.RenameField(
            model_name='_concept',
            old_name='uuid',
            new_name="uuid_id"
        ),
        migrations.RenameField(
            model_name='measure',
            old_name='uuid',
            new_name="uuid_id"
        ),
        migrations.RenameField(
            model_name='organization',
            old_name='uuid',
            new_name="uuid_id"
        ),
        migrations.RenameField(
            model_name='workgroup',
            old_name='uuid',
            new_name="uuid_id"
        ),

        migrations.RunPython(
            create_uuid_objects('aristotle_mdr','measure', migrate_self=True),
            reverse_code=migrations.RunPython.noop
        ),
        migrations.RunPython(
            create_uuid_objects('aristotle_mdr','organization', migrate_self=True),
            reverse_code=migrations.RunPython.noop
        ),
        migrations.RunPython(
            create_uuid_objects('aristotle_mdr','workgroup', migrate_self=True),
            reverse_code=migrations.RunPython.noop
        ),
        migrations.RunPython(
            create_uuid_objects('aristotle_mdr','_concept', migrate_self=True),
            reverse_code=migrations.RunPython.noop
        ),

        migrations.AlterField(
            model_name='_concept',
            name='uuid_id',
            field=models.OneToOneField(default=None, editable=False, help_text='Universally-unique Identifier. Uses UUID1 as this improves uniqueness and tracking between registries', null=True, on_delete=django.db.models.deletion.CASCADE, to='aristotle_mdr.UUID'),
        ),
        migrations.AlterField(
            model_name='measure',
            name='uuid_id',
            field=models.OneToOneField(default=None, editable=False, help_text='Universally-unique Identifier. Uses UUID1 as this improves uniqueness and tracking between registries', null=True, on_delete=django.db.models.deletion.CASCADE, to='aristotle_mdr.UUID'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='uuid_id',
            field=models.OneToOneField(default=None, editable=False, help_text='Universally-unique Identifier. Uses UUID1 as this improves uniqueness and tracking between registries', null=True, on_delete=django.db.models.deletion.CASCADE, to='aristotle_mdr.UUID'),
        ),
        migrations.AlterField(
            model_name='workgroup',
            name='uuid_id',
            field=models.OneToOneField(default=None, editable=False, help_text='Universally-unique Identifier. Uses UUID1 as this improves uniqueness and tracking between registries', null=True, on_delete=django.db.models.deletion.CASCADE, to='aristotle_mdr.UUID'),
        ),


        migrations.RenameField(
            model_name='_concept',
            old_name='uuid_id',
            new_name="uuid"
        ),
        migrations.RenameField(
            model_name='measure',
            old_name='uuid_id',
            new_name="uuid"
        ),
        migrations.RenameField(
            model_name='organization',
            old_name='uuid_id',
            new_name="uuid"
        ),
        migrations.RenameField(
            model_name='workgroup',
            old_name='uuid_id',
            new_name="uuid"
        ),

        migrations.RunSQL(
            migrations.RunSQL.noop,
            reverse_sql='SET CONSTRAINTS ALL IMMEDIATE;'
        ),
    ]
