# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 03:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aristotle_mdr_slots', '0002_lengthen_slot_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slotdefinition',
            name='datatype',
        ),
        migrations.AddField(
            model_name='slot',
            name='name',
            field=models.CharField(default='Slot name lost during migration', max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='slot',
            name='type',
            field=models.CharField(max_length=256, blank=True),
        ),
        migrations.DeleteModel(
            name='SlotDefinition',
        ),
    ]
