# FROM revolutionsystems/python:3.6.3-wee-optimized-lto
FROM python:3.6

# Use the same pip and pipenv as heroku
RUN pip install -U setuptools pip==9.0.2 pipenv==11.8.2 && pip --version && \
    pip install whoosh gunicorn tox
ADD . /usr/src/app
WORKDIR /usr/src/app/docker

ENV DJANGO_SETTINGS_MODULE=settings \
    aristotlemdr__BASE_DIR=/data/ \
    aristotlemdr_STATIC_DIR=/data/staticfiles

RUN sh ./sh/install.sh

RUN mkdir -p /data && mkdir -p /data/staticfiles
EXPOSE 8000

CMD sh ./docker/entrypoint/web.sh
