# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-03 23:44
from __future__ import unicode_literals

from django.db import migrations

def add_slots(apps, schema_editor):
    if apps.is_installed('aristotle_mdr.contrib.slots'):
        slot = apps.get_model('aristotle_mdr.contrib.slots', 'Slot')
        _concept = apps.get_model('aristotle_mdr', '_concept')
        for concept in _concept.objects.all():
            if concept.synonyms:
                slot.objects.create(
                    name='Synonyms',
                    concept=concept,
                    value=concept.synonyms
                )

class Migration(migrations.Migration):

    dependencies = [
        ('aristotle_mdr', '0023_auto_20180206_0332'),
    ]

    operations = [
        migrations.RunPython(add_slots),
        migrations.RemoveField(
            model_name='_concept',
            name='synonyms',
        ),
    ]
