# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-02 06:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import aristotle_mdr.fields

class Migration(migrations.Migration):

    dependencies = [
        ('aristotle_mdr', '0026_auto_20180411_2323'),
    ]

    operations = [
        migrations.CreateModel(
            name='DedDerivesThrough',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(verbose_name='Position')),
            ],
            options={
                'ordering': ['order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DedInputsThrough',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(verbose_name='Position')),
            ],
            options={
                'ordering': ['order'],
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='dataelementderivation',
            name='derives',
        ),
        migrations.RemoveField(
            model_name='dataelementderivation',
            name='inputs',
        ),
        migrations.AddField(
            model_name='dedinputsthrough',
            name='data_element_derivation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aristotle_mdr.DataElementDerivation'),
        ),
        migrations.AddField(
            model_name='dedinputsthrough',
            name='data_element',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aristotle_mdr.DataElement'),
        ),
        migrations.AddField(
            model_name='dedderivesthrough',
            name='data_element_derivation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aristotle_mdr.DataElementDerivation'),
        ),
        migrations.AddField(
            model_name='dedderivesthrough',
            name='data_element',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aristotle_mdr.DataElement'),
        ),
        migrations.AddField(
            model_name='dataelementderivation',
            name='derives',
            field=aristotle_mdr.fields.ConceptManyToManyField(blank=True, help_text='binds with one or more output Data_Elements that are the result of the application of the Data_Element_Derivation.', null=True, related_name='derived_from', through='aristotle_mdr.DedDerivesThrough', to='aristotle_mdr.DataElement'),
        ),
        migrations.AddField(
            model_name='dataelementderivation',
            name='inputs',
            field=aristotle_mdr.fields.ConceptManyToManyField(blank=True, help_text='binds one or more input Data_Element(s) with a Data_Element_Derivation.', related_name='input_to_derivation', through='aristotle_mdr.DedInputsThrough', to='aristotle_mdr.DataElement'),
        ),
    ]
