# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-10 06:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aristotle_mdr', '0028_replace_old_ded_through'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dedderivesthrough',
            unique_together=set([('data_element_derivation', 'data_element')]),
        ),
        migrations.AlterUniqueTogether(
            name='dedinputsthrough',
            unique_together=set([('data_element_derivation', 'data_element')]),
        ),
    ]
