# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-22 02:24
from __future__ import unicode_literals

import aristotle_mdr.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aristotle_mdr', '0030_auto_20180621_0217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='possumprofile',
            name='profilePicture',
            field=aristotle_mdr.fields.ConvertedConstrainedImageField(blank=True, height_field='profilePictureHeight', js_checker=True, max_upload_size=1073741824, mime_lookup_length=4096, null=True, upload_to='', width_field='profilePictureWidth'),
        ),
    ]
